### ISSUE TITLE
La URL del repositorio no es la correcta

### ISSUE THREAD

**Issue by soyricardodev** [midudev/tailwind-animations#25]
La url del repo actualmente es: https://tailwind-animations-ten.vercel.app/
La cual da un error 404 => 
![Screenshot 2024-02-08 at 14-25-48 404 NOT_FOUND](https://github.com/midudev/tailwind-animations/assets/157634505/692a0d64-b24c-4939-b2fe-ddd6715e49e6)
La URL correcta es: 
https://tailwindcss-animations.vercel.app/ =>
![Screenshot 2024-02-08 at 14-26-58 Tailwind CSS Animations Plugin Community-Powered Animation Magic](https://github.com/midudev/tailwind-animations/assets/157634505/53de4716-cf1a-49df-904f-12ad9202e935)

**Comment by Sleepy-gogo** [comment]
Oops, entendí que te referías a la Url del readme, que también estaba mal Jajaj

Si midu ve esto, no creo que le tome mucho corregirla
