### ISSUE TITLE
Background Shine no es una animación del pack de Ibelick

### ISSUE THREAD

**Issue by Sleepy-gogo** [midudev/tailwind-animations#32]
##  Problema

La animación **background shine** que figura en el paquete

![imagen](https://github.com/midudev/tailwind-animations/assets/62667318/aaf4448d-aeb8-40cd-a192-8b84e8e513b2)

No forma parte del pack de animaciones de _Ibelick_. Esta se coló en el paquete, dado que en su website, él la usa para animar la palabra _**animation**_

![imagen](https://github.com/midudev/tailwind-animations/assets/62667318/fca55b8e-2df8-4b76-aa84-90d99d3e6b62)

La misma tendría que ir acompañada de otro set de clases, y por su cuenta no hace demasiado. Por eso es que, en el paquete, pareciera no tener efecto.

## Propongo

- Eliminar la animación del paquete

o

- Hacer que aplique también otras reglas por defecto, como las que acompañan el ejemplo anterior, principalmente el **bg-[length:250%_100%]**, el **bg-clip-text**, y el **text-transparent**:

![imagen](https://github.com/midudev/tailwind-animations/assets/62667318/71544dd2-51dd-4a68-be9e-847cf1b8fcb1)

Esta segunda opción podría ser posible, dado que hay clases en tailwind que aplican más de una regla, como por ejemplo:

![imagen](https://github.com/midudev/tailwind-animations/assets/62667318/5c08413e-da11-42d4-a283-fc7ef3499e93)

**Comment by JosenRomero** [comment]
De momento han eliminado background shine del proyecto, en el commit [Remove background shine ](https://github.com/midudev/tailwind-animations/commit/47b61cea67fef3fa7f4f79595eb5ee8e4471d323)

**Comment by Sleepy-gogo** [comment]
Perfecto, creo que eso sería todo
