### ISSUE TITLE
Could not find a declaration file

### ISSUE THREAD

**Issue by devsmartproject** [midudev/tailwind-animations#52]
Hola,

Estoy usando NEXTJS14 y al momento de colocar la configuración en **tailwind.config.ts**

Tengo el siguiente error!

![image](https://github.com/midudev/tailwind-animations/assets/140632490/c4e9cd13-dc1b-44ba-af6d-bb0471640a3d)

**Comment by soyricardodev** [comment]
si eso tambien pasa con otros plugins de tailwind, para que no te de error hazlo asi

`import { type Config } from 'tailwindcss'

export default {
  ...,
  plugins: [require('@midudev/tailwind-animations')]
} satisfies Config
`

es una solucion mientras se trabaja en las deficiones de tipos

**Comment by devsmartproject** [comment]
Gracias!!!!
